### PR TITLE
PVR: Forward the hints to the codecs

### PR DESCRIPTION
**Pull request by JoeKar**
These changes in combination with this advancedsettings.xml...
https://gist.github.com/JoeKar/5357766
...seem to work for at least some of the SD DVB streams.

Regards, JK

### CODE REVIEW

**Comment by JoeKar** [comment]
So I try to leave my fingers from the core stuff, till I've understood it.

What do you think about the proposed advancedsettings.xml? Because without the PVR flags from the configuration the buffer water-level will be initialized with 10, which seems to be to less.
Unfortunately I'cant use a PR, because my master of buildroot already includes that ldconfig change.

**Comment by davilla** [comment]
you know how to squash in git ?

**Comment by JoeKar** [comment]
Haven't done yet. But I can use google, can read howtos and I'm teachable.

**Comment by davilla** [comment]
git rebase -i <some git hash>, then squash commits together so intermediate commits get rolled into one. then push up to your branch and it will be automatically handled here.

**Comment by JoeKar** [comment]
I will do so and try it with this branch...thanks for the lesson.

**Comment by davilla** [comment]
still something odd, the 1st commit (merge with upstream/master) should not show up. I've pulled this in manually so will also manual close this PR. thx.

**Comment by JoeKar** [comment]
Yes, GitHub takes every time any commit inside a branch as commit for the PR. Also if there is no difference to the destination of the PR.
If I've done something wrong while modifying the PR, please inform me. I've also tried a squash inside this branch/PR, but it didn't work (conflicts while merging)...maybe because of the remote commit.
Sorry for the manual work while merging.

**Comment by davilla** [comment]
NP, manual merge is easy, https://github.com/JoeKar/xbmc/commit/ae847f9440e07905a2e65e7a476d817c2e7e3e73.patch

^^ note the .patch appended to the git hash. this gives you a nice patch that you can then use with 'git am'

**Pull request closed without merging**
