### PR TITLE
[atv] added maxplayerforwardrate to advanced_settings

### PR DESCRIPTION
**Pull request by whaupt**
Hi,
Limiting forward/backward seek speed according to settings (new option) in advancedsettings.xml.
Seeking at more than 4 times of playspeed on SMB-shares, don't work very well for us.

I just wonder if the speed setting is video only (because i put it into video-subtag of advancedsettings)?

Greets wolfi

### CODE REVIEW

**Comment by whaupt** [comment]
i just found out that it is a general player setting, so i've adjusted my implementation a bit.

**Comment by whaupt** [comment]
https://github.com/Pivosgroup/xbmc/commit/6ed8c9bcbedef031067557b2a1d6ddfc246debfe 
fixes the problem for me! thanks @davilla

**Comment by vDorst** [comment]
nice!

**Comment by davilla** [comment]
yep, brainfart that was, D'uh, can you say stack recursion :)

**Comment by whaupt** [comment]
i don't think this is needed anymore.
thx to davilla for the real fix :)

**Pull request closed without merging**
